env:
  DOCKER_IMAGE_ORG_AND_NAME: pactfoundation/pact-cli
  DOCKER_TARGET_PLATFORM: linux/arm64
  TAG: latest

linux_arm64_build_test_task: 
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder-arm64
    architecture: arm64
    platform: linux
    cpu: 2
    memory: 4G
  pre_req_script: |
      apt update --yes && apt install --yes jq
      ./script/release-workflow/docker-prepare.sh
  build_audit_script: |
      ./script/release-workflow/audit.sh
  test_script: |
      ./script/test.sh