version: '{build}'

build_script:
- ps: |
    $ErrorActionPreference="Stop"

    dir C:\projects

    Start-FileDownload https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip -FileName C:\projects\sqfs43-win32.zip

    Start-FileDownload http://enclose.io/rubyc/rubyc-x64.zip -FileName C:\projects\rubyc-x64.zip

    Add-Type -AssemblyName System.IO.Compression.FileSystem

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\sqfs43-win32.zip", "C:\projects\usr\bin")

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\rubyc-x64.zip", "C:\projects\usr\bin")

    mv C:\projects\usr\bin\rubyc-v0.4.0-x64.exe C:\projects\usr\bin\rubyc.exe

test_script:
- cmd: |
    dir C:\

    set PATH=C:\Ruby24\bin;C:\projects\usr\bin;%PATH%

    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64_x86

    where mksquashfs

    mksquashfs -version

    where ruby

    ruby --version

    where gem

    gem --version

    gem install bundler

    where bundle

    bundle --version

    rubyc.exe --output pact.exe --gem=pact-cli --gem-version=0.1.0 pact
