#!/bin/bash
DOCKER_TAG=$(echo "$DOCKER_TAG" | sed 's/^refs\/tags\/v//')
echo "Building version $DOCKER_TAG"
docker buildx create --name multiarch --use

PUSH_IMAGE=${PUSH_IMAGE:-false}
if [ ${PUSH_IMAGE} = "true" ]; then
  PUSH_CMD="--push "
fi
# linux/i386 failing to build
# riscv64/alpine requires a different base image
PLATFORMS_ALPINE=${PLATFORMS_ALPINE:-linux/amd64,linux/arm64,linux/arm,linux/arm/v8,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x}
docker buildx build -t you54f/pact-cli:$DOCKER_TAG --build-arg VERSION=$DOCKER_TAG --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t you54f/pact-cli:latest --build-arg VERSION=$DOCKER_TAG --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t ghcr.io/you54f/pact-cli:$DOCKER_TAG --build-arg VERSION=$DOCKER_TAG --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t ghcr.io/you54f/pact-cli:latest --build-arg VERSION=$DOCKER_TAG --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
# docker buildx build -t you54f/pact-cli:$DOCKER_TAG --build-arg VERSION=$DOCKER_TAG --build-arg BASE_IMAGE=riscv64/alpine:20230901 --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile

