name: Release Docker image

on:
  repository_dispatch:
    types:
      - gem-released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Update gems
      run: |
        gem install bundler -v 2.0.2
        bundle update
        if ! git diff-index --quiet HEAD Gemfile.lock; then
          updated_gems=$(git diff Gemfile.lock | grep + | grep pact | sed -e "s/+ *//" | ruby -e 'puts ARGF.read.split("\n").join(", ")')
          echo "::set-env name=COMMIT_MESSAGE::updated ${updated_gems}"
        fi

    - name: Commit and push gem file changes
      uses: EndBug/add-and-commit@v4
      with:
        add: Gemfile.lock
        author_name: Beth Skurrie via Github Action
        author_email: beth@bethesque.com
        message: 'feat(gems): ${{ env.COMMIT_MESSAGE }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update version and generate changelog
      run: |
        bundle exec bump minor --no-commit
        export VERSION=$(ruby -I lib -e "require 'pact/cli/version.rb'; puts Pact::Cli::VERSION")
        export RELEASE=0
        bundle exec rake generate_changelog
        git diff CHANGELOG.md
        echo "::set-env name=TAG::${VERSION}.${RELEASE}"

    - name: Commit and push version and changelog
      uses: EndBug/add-and-commit@v4
      with:
        add: lib/pact/cli/version.rb Gemfile.lock CHANGELOG.md
        author_name: Beth Skurrie via Github Action
        author_email: beth@bethesque.com
        message: 'chore(release): version ${{ env.TAG }}'
        tag: '${{ env.TAG }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
